export const methods = [
	{
		id: 1,
		name: 'USDT',
		address: 'TLVvNyUUQ5ZGf8ck5R5TBcZd91ftuwBBsg',
		img: 'https://i.ibb.co/xCmrr4n/usdt.png',
		qr: 'https://i.ibb.co/2dtx3df/qrcode1.png',
		title: 'USDT ( TRC-20)',
		isActive: true,
	},
	{
		id: 2,
		name: 'Bitcoin ',
		address: 'bc1qpyx6mmld23qzgla5cedyhpsyh42wkkptrzq33v',
		img: 'https://i.ibb.co/51LzBQT/bit.png',
		qr: 'https://i.ibb.co/2dtx3df/qrcode1.png',
		title: 'Bitcoin',
		isActive: true,
	},
	{
		id: 3,
		name: 'BNB',
		address: '0xb65d56BF5820ee6df2cA50d00cfdDF3E80F4Aa26',
		img: 'https://i.ibb.co/h7C4brr/bnb.png',
		qr: 'https://i.ibb.co/2dtx3df/qrcode1.png',
		title: 'BNB (BSC-20)',
		isActive: false,
	},
	{
		id: 4,
		name: 'Ethereum',
		balance: '0.00',
		address: 'bc1qpyx6mmld23qzgla5cedyhpsyh42wkkptrzq33v',
		img: 'https://i.ibb.co/Jd72Czt/ethereum.png',
		qr: 'https://i.ibb.co/2dtx3df/qrcode1.png',
		title: 'Ethereum (ERC-20))',
		isActive: false,
	},
	// {
	// 	id: 5,
	// 	name: 'Litecoin',
	// 	balance: '0.00',
	// 	address: 'LgfVQJhEJTw4fsDSre6ijJxMoKsBo4b5oP',
	// 	img: 'https://i.ibb.co/rdPrFqc/litacoin.png',
	// 	qr: 'https://i.ibb.co/2dtx3df/qrcode1.png',
	// 	title: 'Litecoin',
	// 	isActive: true,
	// },
];
