import React from 'react';
import TawkMessengerReact from '@tawk.to/tawk-messenger-react';

const TawkTo = () => {
	return (
		<div>
			<TawkMessengerReact
				tawkId='https://tawk.to/chat/63d821e547425128791081a3/1go248qkn'
				tawkKey='1f9b9b9b4704467e89f9f9f9'
				tawkTheme='default'
				tawkLocale='en'
				tawkChatTitle='Chat with us'
				tawkChatMessage='Hi, how can we help you?'
				tawkChatHeader='Welcome to our chat'
				tawkChatHeaderColor='#000000'
				tawkChatHeaderFontSize='20px'
				tawkChatHeaderFontWeight='bold'
				tawkChatHeaderBgColor='#ffffff'
				tawkChatHeaderBorderColor='#000000'
				tawkChatHeaderBorderWidth='1px'
				tawkChatHeaderBorderRadius='5px'
				tawkChatHeaderPadding='10px'
				tawkChatHeaderMargin='10px'
				tawkChatHeaderPosition='bottom'
				tawkChatHeaderShow='true'
				tawkChatHeaderClose='true'
				tawkChatHeaderCloseColor='#000000'
				tawkChatHeaderCloseSize='20px'
				tawkChatHeaderClosePosition='right'
				tawkChatHeaderCloseMargin='10px'
				tawkChatHeaderClosePadding='10px'
				tawkChatHeaderCloseBorderRadius='50%'
				tawkChatHeaderCloseBgColor='#ffffff'
				tawkChatHeaderCloseBorderWidth='1px'
				tawkChatHeaderCloseBorderColor='#000000'
				tawkChatHeaderCloseHoverBgColor='#000000'
				tawkChatHeaderCloseHoverColor='#ffffff'
				tawkChatHeaderCloseHoverBorderWidth='1px'
				tawkChatHeaderCloseHoverBorderColor='#000000'
				tawkChatHeaderCloseHoverBorderRadius='50%'
				tawkChatHeaderCloseHoverPadding='10px'
				tawkChatHeaderCloseHoverMargin='10px'
				tawkChatHeaderCloseHoverSize='20px'
				tawkChatHeaderCloseHoverPosition='right'
				tawkChatHeaderCloseHoverShow='true'
				tawkChatHeaderCloseHoverClose='true'
				tawkChatHeaderCloseHoverCloseColor='#000000'
				tawkChatHeaderCloseHoverCloseSize='20px'
				tawkChatHeaderCloseHoverClosePosition='right'
				tawkChatHeaderCloseHoverCloseMargin='10px'
				tawkChatHeaderCloseHoverClosePadding='10px'
				tawkChatHeaderCloseHoverCloseBorderRadius='50%'
				tawkChatHeaderCloseHoverCloseBgColor='#ffffff'
				tawkChatHeaderCloseHoverCloseBorderWidth='1px'
				tawkChatHeaderCloseHoverCloseBorderColor='#000000'
				tawkChatHeaderCloseHoverCloseHoverBgColor='#000000'
				tawkChatHeaderCloseHoverCloseHoverColor='#ffffff'
				tawkChatHeaderCloseHoverCloseHoverBorderWidth='1px'
				tawkChatHeaderCloseHoverCloseHoverBorderColor='#000000'
				tawkChatHeaderCloseHoverCloseHoverBorderRadius='50%'
				tawkChatHeaderCloseHoverCloseHoverPadding='10px'
				tawkChatHeaderCloseHoverCloseHoverMargin='10px'
				tawkChatHeaderCloseHoverCloseHoverSize='20px'
				tawkChatHeaderCloseHoverCloseHoverPosition='right'
				tawkChatHeaderCloseHoverCloseHoverShow='true'
				tawkChatHeaderCloseHoverCloseHoverClose='true'
				tawkChatHeaderCloseHoverCloseHoverCloseColor='#000000'
				tawkChatHeaderCloseHoverCloseHoverCloseSize='20px'
				tawkChatHeaderCloseHoverCloseHoverClosePosition='right'
				tawkChatHeaderCloseHoverCloseHoverCloseMargin='10px'
				tawkChatHeaderCloseHoverCloseHoverClosePadding='10px'
				tawkChatHeaderCloseHoverCloseHoverCloseBorderRadius='50%'
				tawkChatHeaderCloseHoverCloseHoverCloseBgColor='#ffffff'
				tawkChatHeaderCloseHoverCloseHoverCloseBorderWidth='1px'
				tawkChatHeaderCloseHoverCloseHoverCloseBorderColor='#000000'
			/>
		</div>
	);
};

export default TawkTo;
